### ISSUE TITLE
Server Status relocated?

### ISSUE THREAD

**Issue by fosspill** [NotFakeAdam/SplitgateResearch#1]
Hey!

I found this project and find it really interesting. However, the server status api call seems to be outdated. Presumably they've added a new one - or moved it somewhere else.

Could you give me any pointers about how you found these, so that I may try to figure this one out?

**Comment by Henrik-3** [comment]
For me https://api.splitgate.com/server-status and https://api.splitgate.com/server-status?encodedCompositePlatformId=INSERT-OWN-JWT-HERE seems to work fine

**Comment by fosspill** [comment]
Alright, thank you! I see this is a bit over my head now and google hasn't helped much. Where is my own jwt stored in this case?

**Comment by Henrik-3** [comment]
U can find it in the logs (AppData/Local/PortalWars/Saved/Logs) when u enter the queue one time, so you have to search for it, but in general there is basicly no data in this endpoint sadly :C

**Comment by Henrik-3** [comment]
`{
  "isLive": false,
  "errorCode": "servers-offline",
  "errorText": {
    "en": "You have been placed in a queue to prevent our servers from going above capacity. Follow @splitgate on Twitter for updates. Thanks for being patient <3"
  },
  "retryInMs": 10000
}`

I mean thats all

**Comment by fosspill** [comment]
I see, so it's basically useless. My hope was that there would be some queue information available, but I guess not.

Thank you!
